### PR TITLE
Adding contact page in spanish

### PR DESCRIPTION
**Pull request by MrOldSchool66**
I have added the contact page for the spanish users in spanish and created the link for all the other subpages

### CODE REVIEW

**Comment by javipepe** [comment]
The links are wrong.  They are heading to <code>/lang/es/overcast</code> instead of <code>/lang/es/contact</code>.  Also the titles of the Spanish contact page are not translated. 

Fix that and I'll merge.  Thanks nevertheless :smiley:

**Comment by MrOldSchool66** [comment]
Ooops. I'll fix it now

**Comment by MrOldSchool66** [comment]
Now I think it's ready

**Comment by javipepe** [comment]
Thanks a lot.

**Comment by javipepe** [comment]
@MrOldSchool66 could you please create a new pull request and remove all the '+' in the Spanish contact page?

**Pull request merged**
